import { faBox, faBoxes, faCartShopping, faChartLine, faChartPie, faHashtag, faReceipt, faUsers, faUserTie, faWallet } from '@fortawesome/free-solid-svg-icons'

export const mainSidebars = [
    {
        type: 'item',
        route: 'overview',
        icon: faChartPie,
        label: 'Ringkasan',
        permissions: [],
        activeRoute: 'overview',
    },
    {
        type: 'item',
        route: '#',
        icon: faReceipt,
        label: 'Penjualan',
        permissions: [],
        activeRoute: 'sales',
    },
    {
        type: 'dropdown',
        route: '#',
        icon: faBox,
        label: 'Master Produk',
        permissions: [],
        activeRoute: 'master.',
        items: [
            {
                type: 'item',
                route: 'master.categories.index',
                label: 'Kategori Produk',
                permissions: [],
                activeRoute: 'master.categories.',
            },
            {
                type: 'item',
                route: 'master.products.index',
                label: 'Produk Jual',
                permissions: [],
                activeRoute: 'master.products.',
            },
            {
                type: 'item',
                route: 'master.modifiers.index',
                label: 'Opsi Tambahan',
                permissions: [],
                activeRoute: 'master.modifiers.',
            },
        ],
    },
    {
        type: 'dropdown',
        route: '#',
        icon: faBoxes,
        label: 'Inventori',
        permissions: [],
        activeRoute: 'inventories.',
        items: [
            {
                type: 'item',
                route: '#',
                label: 'Stok',
                permissions: [],
                activeRoute: 'inventories.stock.',
            },
            {
                type: 'item',
                route: '#',
                label: 'Pemasok / Supplier',
                permissions: [],
                activeRoute: 'inventories.suppliers.',
            },
            {
                type: 'item',
                route: '#',
                label: 'Pesanan Pembelian (PO)',
                permissions: [],
                activeRoute: 'inventories.po.',
            },
            {
                type: 'item',
                route: '#',
                label: 'Stok Opname',
                permissions: [],
                activeRoute: 'inventories.stock-taking.',
            },
            {
                type: 'item',
                route: '#',
                label: 'Stok Retur',
                permissions: [],
                activeRoute: 'inventories.return.',
            },
            {
                type: 'item',
                route: '#',
                label: 'Mutasi Stok',
                permissions: [],
                activeRoute: 'inventories.transfers.',
            },
            {
                type: 'item',
                route: '#',
                label: 'Konversi Stok',
                permissions: [],
                activeRoute: 'inventories.conversion.',
            },
        ],
    },
    {
        type: 'item',
        route: '#',
        icon: faCartShopping,
        label: 'Pesanan / Order',
        permissions: [],
        activeRoute: 'orders',
    },
    {
        type: 'item',
        route: '#',
        icon: faUsers,
        label: 'Pelanggan',
        permissions: [],
        activeRoute: 'members',
    },
    {
        type: 'item',
        route: 'employees.index',
        icon: faUserTie,
        label: 'Pegawai',
        permissions: ['user.view'],
        activeRoute: 'employees',
    },
    {
        type: 'dropdown',
        route: '#',
        icon: faWallet,
        label: 'Keuangan',
        permissions: [],
        activeRoute: 'finance',
        items: [
            {
                type: 'item',
                route: '#',
                label: 'Penjualan Harian',
                permissions: [],
                activeRoute: 'finance.daily-sales.',
            },
            {
                type: 'item',
                route: '#',
                label: 'Pembayaran',
                permissions: [],
                activeRoute: 'finance.payments.',
            },
            {
                type: 'item',
                route: '#',
                label: 'Pengembalian Dan Diskon',
                permissions: [],
                activeRoute: 'finance.refund-discount.',
            },
        ],
    },
    {
        type: 'dropdown',
        route: '#',
        icon: faChartLine,
        label: 'Laporan',
        permissions: [],
        activeRoute: 'reports',
        items: [
            {
                type: 'item',
                route: '#',
                label: 'Penjualan Produk',
                permissions: [],
                activeRoute: 'reports.products.',
            },
            {
                type: 'item',
                route: '#',
                label: 'Stok',
                permissions: [],
                activeRoute: 'reports.stock.',
            },
            {
                type: 'item',
                route: '#',
                label: 'Pegawai',
                permissions: [],
                activeRoute: 'reports.employees.',
            },
            {
                type: 'item',
                route: '#',
                label: 'Retur',
                permissions: [],
                activeRoute: 'reports.return.',
            },
            {
                type: 'item',
                route: '#',
                label: 'Pajak & Diskon',
                permissions: [],
                activeRoute: 'reports.tax-discounts.',
            },
            {
                type: 'item',
                route: '#',
                label: 'Omset',
                permissions: [],
                activeRoute: 'reports.revenue.',
            },
        ],
    },
    {
        type: 'dropdown',
        route: '#',
        icon: faHashtag,
        label: 'Template',
        permissions: [],
        activeRoute: 'template',
        items: [
            {
                type: 'item',
                route: 'template.form',
                label: 'Form',
                permissions: [],
                activeRoute: 'template.form',
            },
            {
                type: 'item',
                route: 'template.cards',
                label: 'Card',
                permissions: [],
                activeRoute: 'template.cards',
            },
            {
                type: 'item',
                route: 'template.navigation',
                label: 'Navigation & Tab',
                permissions: [],
                activeRoute: 'template.navigation',
            },
            {
                type: 'item',
                route: 'template.buttons',
                label: 'Buttons',
                permissions: [],
                activeRoute: 'template.buttons',
            },
            {
                type: 'item',
                route: 'template.charts',
                label: 'Charts',
                permissions: [],
                activeRoute: 'template.charts',
            },
            {
                type: 'item',
                route: 'template.notifications',
                label: 'Notifications',
                permissions: [],
                activeRoute: 'template.notifications',
            },
            {
                type: 'item',
                route: 'template.widgets',
                label: 'Widgets',
                permissions: [],
                activeRoute: 'template.widgets',
            },
        ],
    },
]
