import { faArrowLeft, faBoxes, faCashRegister, faCog, faCreditCard, faGears, faHistory, faHome, faInfo, faMapMarkerAlt, faMarker, faMoneyBill, faMoneyBills, faReceipt, faShop, faUser, faUserCircle, faUserShield, faWallet, faXmarkCircle } from '@fortawesome/free-solid-svg-icons'

export const settingSidebars = [
    {
        type: 'section',
        label: 'Pengaturan',
        separator: false,
    },
    {
        type: 'item',
        route: 'settings.account.profile',
        icon: faUserCircle,
        label: 'Pusat Akun',
        permissions: [],
        activeRoute: 'settings.account',
    },
    {
        type: 'section',
        label: 'Usaha & Langganan',
        separator: true,
    },
    {
        type: 'item',
        route: 'settings.business.detail',
        icon: faShop,
        label: 'Detail Usaha',
        permissions: ['business.view'],
        activeRoute: 'settings.business',
    },
    {
        type: 'item',
        route: 'settings.outlets.index',
        icon: faMapMarkerAlt,
        label: 'Outlet',
        permissions: ['outlet.view'],
        activeRoute: 'settings.outlets',
    },
    {
        type: 'item',
        route: 'settings.billing.index',
        icon: faCreditCard,
        label: 'Langganan & Tagihan',
        permissions: ['business.billing'],
        activeRoute: 'settings.billing',
    },
    {
        type: 'section',
        label: 'Pengaturan Umum',
        separator: true,
    },
    {
        type: 'item',
        route: '#',
        icon: faCog,
        label: 'Konfigurasi Umum',
        permissions: [],
        activeRoute: 'settings.config',
    },
    {
        type: 'item',
        route: '#',
        icon: faCashRegister,
        label: 'Pengaturan Kasir',
        permissions: [],
        activeRoute: 'settings.cashier',
    },
    {
        type: 'item',
        route: '#',
        icon: faReceipt,
        label: 'Nota',
        permissions: [],
        activeRoute: 'settings.receipt',
    },
    {
        type: 'item',
        route: '#',
        icon: faBoxes,
        label: 'Inventori',
        permissions: [],
        activeRoute: 'settings.inventory',
    },
    {
        type: 'item',
        route: '#',
        icon: faUserShield,
        label: 'Hak Akses',
        permissions: [],
        activeRoute: 'settings.roles',
    },
]
