import { faArrowLeft, faBoxes, faCalculator, faCashRegister, faClock, faCog, faCreditCard, faGears, faHistory, faHome, faInfo, faMapMarkerAlt, faMarker, faMinus, faMinusSquare, faMoneyBill, faMoneyBills, faReceipt, faShop, faUser, faUserCircle, faUserShield, faWallet, faXmarkCircle } from '@fortawesome/free-solid-svg-icons'

export const settingSidebars = [
    {
        type: 'section',
        label: 'Pengaturan',
        separator: false,
    },
    {
        type: 'item',
        url: route('settings.account.profile'),
        icon: faUserCircle,
        label: 'Pusat Akun',
        permissions: [],
        activeRoute: 'settings.account',
    },
    {
        type: 'section',
        label: 'Usaha & Langganan',
        separator: true,
    },
    {
        type: 'item',
        url: route('settings.business.detail'),
        icon: faShop,
        label: 'Informasi Usaha',
        permissions: ['business.view'],
        activeRoute: 'settings.business',
    },
    {
        type: 'item',
        url: route('settings.outlets.index'),
        icon: faMapMarkerAlt,
        label: 'Outlet',
        permissions: ['outlet.view'],
        activeRoute: 'settings.outlets',
    },
    {
        type: 'item',
        url: route('settings.billing.index'),
        icon: faCreditCard,
        label: 'Langganan & Tagihan',
        permissions: ['business.billing'],
        activeRoute: 'settings.billing',
    },
    {
        type: 'section',
        label: 'Pengaturan Operasional & POS',
        separator: true,
    },
    {
        type: 'item',
        url: route('settings.operational.index'),
        icon: faClock,
        label: 'Jam Operasional',
        permissions: ['outlet.view'],
        activeRoute: 'settings.operational',
    },
    {
        type: 'item',
        url: route('settings.devices.index'),
        icon: faCashRegister,
        label: 'Perangkat',
        permissions: ['setting.device', 'outlet.view'],
        activeRoute: 'settings.devices',
    },
    {
        type: 'item',
        url: route('settings.receipt.index'),
        icon: faReceipt,
        label: 'Layout Struk & Nota',
        permissions: ['setting.receipt', 'outlet.view'],
        activeRoute: 'settings.receipt',
    },
    {
        type: 'item',
        url: route('settings.taxes.index'),
        icon: faCalculator,
        label: 'Pajak & Biaya',
        permissions: ['setting.tax', 'outlet.view'],
        activeRoute: 'settings.taxes',
    },
    {
        type: 'item',
        url: route('settings.payment-methods.index'),
        icon: faCreditCard,
        label: 'Metode Pembayaran',
        permissions: ['setting.payment'],
        activeRoute: 'settings.payment-methods',
    },
    {
        type: 'item',
        url: '#',
        icon: faUserShield,
        label: 'Hak Akses',
        permissions: [],
        activeRoute: 'settings.roles',
    },
    {
        type: 'item',
        url: '#',
        icon: faHistory,
        label: 'Log Aktivitas',
        permissions: [],
        activeRoute: 'settings.audit-logs',
    },
]
