import { faArrowLeft, faBoxes, faCalculator, faCashRegister, faCog, faCreditCard, faGears, faHistory, faHome, faInfo, faMapMarkerAlt, faMarker, faMinus, faMinusSquare, faMoneyBill, faMoneyBills, faReceipt, faShop, faUser, faUserCircle, faUserShield, faWallet, faXmarkCircle } from '@fortawesome/free-solid-svg-icons'

export const settingSidebars = [
    {
        type: 'section',
        label: 'Pengaturan',
        separator: false,
    },
    {
        type: 'item',
        url: route('settings.account.profile'),
        icon: faUserCircle,
        label: 'Pusat Akun',
        permissions: [],
        activeRoute: 'settings.account',
    },
    {
        type: 'section',
        label: 'Usaha & Langganan',
        separator: true,
    },
    {
        type: 'item',
        url: route('settings.business.detail'),
        icon: faShop,
        label: 'Informasi Usaha',
        permissions: ['business.view'],
        activeRoute: 'settings.business',
    },
    {
        type: 'item',
        url: route('settings.outlets.index'),
        icon: faMapMarkerAlt,
        label: 'Outlet',
        permissions: ['outlet.view'],
        activeRoute: 'settings.outlets',
    },
    {
        type: 'item',
        url: route('settings.billing.index'),
        icon: faCreditCard,
        label: 'Langganan & Tagihan',
        permissions: ['business.billing'],
        activeRoute: 'settings.billing',
    },
    {
        type: 'section',
        label: 'Pengaturan',
        separator: true,
    },
    {
        type: 'item',
        url: '#',
        icon: faCog,
        label: 'Konfigurasi Umum',
        permissions: [],
        activeRoute: 'settings.config',
    },
    {
        type: 'item',
        url: '#',
        icon: faCashRegister,
        label: 'Perangkat',
        permissions: [],
        activeRoute: 'settings.cashier',
    },
    {
        type: 'item',
        url: '#',
        icon: faReceipt,
        label: 'Nota',
        permissions: [],
        activeRoute: 'settings.receipt',
    },
    {
        type: 'item',
        url: '#',
        icon: faCalculator,
        label: 'Pajak & Potongan',
        permissions: [],
        activeRoute: 'settings.inventory',
    },
    {
        type: 'item',
        url: route('settings.payment-methods.index'),
        icon: faCreditCard,
        label: 'Metode Pembayaran',
        permissions: ['setting.payment'],
        activeRoute: 'settings.payment-methods',
    },
    {
        type: 'item',
        url: '#',
        icon: faUserShield,
        label: 'Hak Akses',
        permissions: [],
        activeRoute: 'settings.roles',
    },
    {
        type: 'item',
        url: '#',
        icon: faHistory,
        label: 'Log Aktivitas',
        permissions: [],
        activeRoute: 'settings.roles',
    },
]
