import { faBox, faBoxes, faCartShopping, faChartLine, faChartPie, faHashtag, faReceipt, faUsers, faUserTie, faWallet } from "@fortawesome/free-solid-svg-icons";

export const mainSidebars = [
    {
        route: "overview",
        icon: faChartPie,
        label: "Ringkasan",
        permissions: "",
        activeRoute: "dashboard.overview",
    },
    {
        route: "#",
        icon: faReceipt,
        label: "Penjualan",
        permissions: "",
        activeRoute: "sales",
    },
    {
        route: "#",
        icon: faBox,
        label: "Produk",
        permissions: [],
        activeRoute: "products.",
        items: [
            {
                route: "products.units.index",
                label: "Satuan",
                permissions: [],
                activeRoute: "products.units.",
            },
            {
                route: "products.categories.index",
                label: "Kategori",
                permissions: [],
                activeRoute: "products.categories.",
            },
            {
                route: "#",
                label: "Varian",
                permissions: [],
                activeRoute: "products.variations.",
            },
            {
                route: "#",
                label: "Varian",
                permissions: [],
                activeRoute: "products.variations.",
            },
            {
                route: "#",
                label: "Data Produk",
                permissions: [],
                activeRoute: "products.products.",
            },
        ],
    },
    {
        route: "#",
        icon: faBoxes,
        label: "Inventori",
        permissions: [],
        activeRoute: "inventories.",
        items: [
            {
                route: "#",
                label: "Stok",
                permissions: [],
                activeRoute: "inventories.stock.",
            },
            {
                route: "#",
                label: "Pemasok / Supplier",
                permissions: [],
                activeRoute: "inventories.suppliers.",
            },
            {
                route: "#",
                label: "Pesanan Pembelian (PO)",
                permissions: [],
                activeRoute: "inventories.po.",
            },
            {
                route: "#",
                label: "Stok Opname",
                permissions: [],
                activeRoute: "inventories.stock-taking.",
            },
            {
                route: "#",
                label: "Stok Retur",
                permissions: [],
                activeRoute: "inventories.return.",
            },
            {
                route: "#",
                label: "Mutasi Stok",
                permissions: [],
                activeRoute: "inventories.transfers.",
            },
            {
                route: "#",
                label: "Konversi Stok",
                permissions: [],
                activeRoute: "inventories.conversion.",
            },
        ],
    },
    {
        route: "#",
        icon: faCartShopping,
        label: "Pesanan / Order",
        permissions: [],
        activeRoute: "orders",
    },
    {
        route: "#",
        icon: faUsers,
        label: "Pelanggan",
        permissions: [],
        activeRoute: "members",
    },
    {
        route: "employees.index",
        icon: faUserTie,
        label: "Pegawai",
        permissions: ["user.view"],
        activeRoute: "employees",
    },
    {
        route: "#",
        icon: faWallet,
        label: "Keuangan",
        permissions: [],
        activeRoute: "finance",
        items: [
            {
                route: "#",
                label: "Penjualan Harian",
                permissions: [],
                activeRoute: "finance.daily-sales.",
            },
            {
                route: "#",
                label: "Pembayaran",
                permissions: [],
                activeRoute: "finance.payments.",
            },
            {
                route: "#",
                label: "Pengembalian Dan Diskon",
                permissions: [],
                activeRoute: "finance.refund-discount.",
            },
        ],
    },
    {
        route: "#",
        icon: faChartLine,
        label: "Laporan",
        permissions: [],
        activeRoute: "reports",
        items: [
            {
                route: "#",
                label: "Penjualan Produk",
                permissions: [],
                activeRoute: "reports.products.",
            },
            {
                route: "#",
                label: "Stok",
                permissions: [],
                activeRoute: "template.form",
            },
            {
                route: "#",
                label: "Pegawai",
                permissions: [],
                activeRoute: "reports.employees.",
            },
            {
                route: "#",
                label: "Retur",
                permissions: [],
                activeRoute: "reports.return.",
            },
            {
                route: "#",
                label: "Pajak & Diskon",
                permissions: [],
                activeRoute: "reports.tax-discounts.",
            },
            {
                route: "#",
                label: "Omset",
                permissions: [],
                activeRoute: "reports.revenue.",
            },
        ],
    },
    {
        route: "#",
        icon: faHashtag,
        label: "Template",
        permissions: [],
        activeRoute: "template",
        items: [
            {
                route: "template.form",
                label: "Form",
                permissions: [],
                activeRoute: "template.form",
            },
            {
                route: "template.cards",
                label: "Card",
                permissions: [],
                activeRoute: "template.form",
            },
            {
                route: "template.navigation",
                label: "Navigation & Tab",
                permissions: [],
                activeRoute: "template.navigation",
            },
            {
                route: "template.buttons",
                label: "Buttons",
                permissions: [],
                activeRoute: "template.buttons",
            },
            {
                route: "template.charts",
                label: "Charts",
                permissions: [],
                activeRoute: "template.charts",
            },
            {
                route: "template.notifications",
                label: "Notifications",
                permissions: [],
                activeRoute: "template.notifications",
            },
            {
                route: "template.widgets",
                label: "Widgets",
                permissions: [],
                activeRoute: "template.widgets",
            },
        ],
    },
];
